# Generated by Django 3.1.7 on 2021-04-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('vendorСode', models.CharField(max_length=120, verbose_name='Артикул')),
                ('title', models.CharField(max_length=120, verbose_name='Имя товара')),
                ('description', models.TextField(max_length=1200)),
                ('prise1', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена(если 2 объема, цена за меньший)')),
                ('img', models.ImageField(default='default.png', upload_to='goods_img')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBestsellers',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('2_volume', models.BooleanField(default=True, verbose_name='Наличие 2ух объемов')),
                ('volume1', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='объем(меньший)')),
                ('volume2', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='объем(больший)')),
                ('prise2', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='цена за больший объем')),
                ('aromat', models.CharField(max_length=120, verbose_name='аромат')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('2_volume', models.BooleanField(default=True, verbose_name='Наличие 2ух объемов')),
                ('volume1', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='объем(меньший)')),
                ('volume2', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='объем(больший)')),
                ('prise2', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='цена за больший объем')),
            ],
            bases=('shop.product',),
        ),
    ]
