# Generated by Django 3.1.7 on 2021-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productset',
            name='volume1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='объем(меньший)'),
        ),
    ]
