# Generated by Django 3.1.7 on 2021-04-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210407_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productset',
            options={'verbose_name': 'Что-то твое на русском на родном', 'verbose_name_plural': 'Что-то твое на русском на родном'},
        ),
    ]
