# Generated by Django 3.1.7 on 2021-04-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210407_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productset',
            options={'verbose_name': 'Что-то твое на русском на родном'},
        ),
    ]
