# Generated by Django 3.1.7 on 2021-04-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210407_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '1Категории', 'verbose_name_plural': '1Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '0Весь ассортимент', 'verbose_name_plural': '0Весь ассортимент'},
        ),
        migrations.AlterModelOptions(
            name='productbestsellers',
            options={'verbose_name': 'Бестселлеры', 'verbose_name_plural': 'Бестселлеры'},
        ),
        migrations.AlterModelOptions(
            name='productset',
            options={'verbose_name': 'Наборы', 'verbose_name_plural': 'Наборы'},
        ),
        migrations.AlterField(
            model_name='productbestsellers',
            name='volume1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='объем(меньший)'),
        ),
    ]
