# Generated by Django 3.1.7 on 2021-04-08 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210407_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('quantity', models.IntegerField(default=1)),
                ('article_date', models.DateTimeField(default=datetime.datetime(2021, 4, 8, 15, 45, 30, 842196))),
            ],
        ),
    ]
